import pytest
import glob
from parsers.case_details import CaseDetails
from entities import Case, Party, Business, HistoryEntry, Order, Objection
import datetime
import os
import wat


@pytest.fixture
def case_details_html():
    with open("test/fixtures/html/HCP-JKHC02-011375-2018.html") as f:
        return f.read()


def test_case_details_parser(case_details_html):
    case_details = CaseDetails(case_details_html)
    expected = Case(
        case_type="HCP",
        filing_number="9702/2018",
        registration_number="58/2018",
        registration_date=datetime.date(2018, 12, 29),
        cnr_number="JKHC02-011375-2018",
        first_hearing_date=datetime.date(2018, 12, 31),
        decision_date=datetime.date(2020, 12, 24),
        case_status="CASE DISPOSED",
        nature_of_disposal="Uncontested--Dismissed",
        coram="1712HON'BLE MR.  JUSTICE SANJAY DHAR",
        bench="Single Bench",
        state="JAMMUKASHMIR",
        district="SRINAGAR",
        judicial="HABEUS CORPUS PETITION (HCP)",
        petitioners=[Party(name="ASHRAM HUSSAIN")],
        respondents=[Party(name="STATE TH.HOME DEPTT.AND ORS.")],
        orders=[
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                date=datetime.date(2019, 2, 26),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4WZk9SNDiELN0d3zciW0Jd2",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                date=datetime.date(2019, 4, 3),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4VfQwf0orUZaOPgJQdtRngq",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR. JUSTICE ALI MOHAMMAD MAGREY",
                date=datetime.date(2019, 7, 8),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4W9zkSacwsce/3OpGJvB0lg",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR. JUSTICE ALI MOHAMMAD MAGREY",
                date=datetime.date(2019, 7, 8),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4V4B7CAX6YboIYTxzyrEv0a",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE  MR. JUSTICE RAJESH BINDAL",
                date=datetime.date(2019, 9, 11),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4UBDlNqL/zLUzTp/PjCG3fg",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                date=datetime.date(2019, 10, 14),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4VVwZkC6SFsMLeD82pm02mP",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR. JUSTICE SANJEEV KUMAR",
                date=datetime.date(2020, 2, 28),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4VKAoANwWy5ZhRhsffy1Wdy",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR.  JUSTICE SANJAY DHAR",
                date=datetime.date(2020, 10, 19),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4WYPfx2WudNMAu4SDcElc+g",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
            Order(
                caseno="HCP/58/2018",
                judge="HON'BLE MR.  JUSTICE SANJAY DHAR",
                date=datetime.date(2020, 12, 24),
                filename="rC8SUFuyEFsvB5V61cXUrLSLzKEH6Vx/wvYTxzlyF4Uu7tOArEmvxZv7juS7VWPW",
                cCode="1",
                cino="JKHC020113752018",
                state_code="12",
                appFlag=None,
            ),
        ],
        history=[
            HistoryEntry(
                cause_list_type=None,
                judge="HON'BLE MR.  JUSTICE SANJAY DHAR",
                business_on_date=datetime.date(2020, 12, 24),
                hearing_date=None,
                purpose_of_hearing="Disposed",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=None,
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="Disposed",
                    businessDate=datetime.date(2020, 12, 24),
                    court_no="1712",
                    srno="0",
                ),
            ),
            HistoryEntry(
                cause_list_type=None,
                judge="",
                business_on_date=None,
                hearing_date=datetime.date(2018, 12, 31),
                purpose_of_hearing="FOR ADMISSION After Notice",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2018, 12, 31),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=None,
                    court_no="0",
                    srno="1",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2018, 12, 31),
                hearing_date=datetime.date(2019, 1, 17),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 1, 17),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2018, 12, 31),
                    court_no="1480",
                    srno="2",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MRS. JUSTICE SINDHU SHARMA",
                business_on_date=datetime.date(2019, 1, 17),
                hearing_date=datetime.date(2019, 1, 29),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 1, 29),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 1, 17),
                    court_no="1487",
                    srno="3",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 1, 29),
                hearing_date=datetime.date(2019, 2, 26),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 2, 26),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 1, 29),
                    court_no="1490",
                    srno="4",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 2, 26),
                hearing_date=datetime.date(2019, 4, 3),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 4, 3),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 2, 26),
                    court_no="1515",
                    srno="5",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 4, 3),
                hearing_date=datetime.date(2019, 4, 26),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 4, 26),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 4, 3),
                    court_no="1553",
                    srno="6",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 4, 26),
                hearing_date=datetime.date(2019, 5, 6),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 5, 6),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 4, 26),
                    court_no="1576",
                    srno="7",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 5, 6),
                hearing_date=datetime.date(2019, 7, 8),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 7, 8),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 5, 6),
                    court_no="1704",
                    srno="8",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE ALI MOHAMMAD MAGREY",
                business_on_date=datetime.date(2019, 7, 8),
                hearing_date=datetime.date(2019, 8, 5),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 8, 5),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 7, 8),
                    court_no="1703",
                    srno="9",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 8, 5),
                hearing_date=datetime.date(2019, 9, 11),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 9, 11),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 8, 5),
                    court_no="1704",
                    srno="10",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE  MR. JUSTICE RAJESH BINDAL",
                business_on_date=datetime.date(2019, 9, 11),
                hearing_date=datetime.date(2019, 10, 14),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 10, 14),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 9, 11),
                    court_no="1702",
                    srno="11",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 10, 14),
                hearing_date=datetime.date(2019, 11, 4),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 11, 4),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 10, 14),
                    court_no="1704",
                    srno="12",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE DHIRAJ SINGH THAKUR",
                business_on_date=datetime.date(2019, 11, 4),
                hearing_date=datetime.date(2019, 12, 4),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 12, 4),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 11, 4),
                    court_no="1704",
                    srno="13",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE  MR. JUSTICE RAJESH BINDAL",
                business_on_date=datetime.date(2019, 12, 4),
                hearing_date=datetime.date(2019, 12, 27),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2019, 12, 27),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 12, 4),
                    court_no="1702",
                    srno="14",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE ALI MOHAMMAD MAGREY",
                business_on_date=datetime.date(2019, 12, 27),
                hearing_date=datetime.date(2020, 2, 28),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 2, 28),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2019, 12, 27),
                    court_no="1703",
                    srno="15",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE SANJEEV KUMAR",
                business_on_date=datetime.date(2020, 2, 28),
                hearing_date=datetime.date(2020, 4, 21),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 4, 21),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 2, 28),
                    court_no="1706",
                    srno="16",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR.  JUSTICE PUNEET GUPTA",
                business_on_date=datetime.date(2020, 4, 21),
                hearing_date=datetime.date(2020, 8, 11),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 8, 11),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 4, 21),
                    court_no="1713",
                    srno="17",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE RAJNESH OSWAL",
                business_on_date=datetime.date(2020, 8, 11),
                hearing_date=datetime.date(2020, 9, 11),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 9, 11),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 8, 11),
                    court_no="1710",
                    srno="18",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE RAJNESH OSWAL",
                business_on_date=datetime.date(2020, 9, 11),
                hearing_date=datetime.date(2020, 9, 22),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 9, 22),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 9, 11),
                    court_no="1710",
                    srno="19",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR. JUSTICE RAJNESH OSWAL",
                business_on_date=datetime.date(2020, 9, 22),
                hearing_date=datetime.date(2020, 10, 5),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 10, 5),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 9, 22),
                    court_no="1710",
                    srno="20",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR.  JUSTICE SANJAY DHAR",
                business_on_date=datetime.date(2020, 10, 5),
                hearing_date=datetime.date(2020, 10, 19),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 10, 19),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 10, 5),
                    court_no="1712",
                    srno="21",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR.  JUSTICE SANJAY DHAR",
                business_on_date=datetime.date(2020, 10, 19),
                hearing_date=datetime.date(2020, 12, 7),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 7),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 10, 19),
                    court_no="1712",
                    srno="22",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HON'BLE MR.  JUSTICE SANJAY DHAR",
                business_on_date=datetime.date(2020, 12, 7),
                hearing_date=datetime.date(2020, 12, 24),
                purpose_of_hearing="SPECIALLY ORDERED CASES",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="Order on",
                business_on_date=None,
                hearing_date=None,
                purpose_of_hearing="Order Details",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2019, 2, 26),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2019, 4, 3),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2019, 7, 8),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2019, 7, 8),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2019, 9, 11),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2019, 10, 14),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2020, 2, 28),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2020, 10, 19),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
            HistoryEntry(
                cause_list_type=True,
                judge="HCP/58/2018",
                business_on_date=None,
                hearing_date=datetime.date(2020, 12, 24),
                purpose_of_hearing="View",
                business=Business(
                    court_code="1",
                    dist_code="1",
                    nextdate1=datetime.date(2020, 12, 24),
                    case_number1="201700000582018",
                    state_code="12",
                    disposal_flag="DisposedP",
                    businessDate=datetime.date(2020, 12, 7),
                    court_no="1712",
                    srno="23",
                ),
            ),
        ],
        category="SB HABEAS CORPUS PETITION ( 107 )",
        sub_category="OTHER MATTERS ( 99 )",
        objections=[
            Objection(
                scrutiny_date=datetime.date(2018, 12, 29),
                objection="All Objections are Complied",
                compliance_date=None,
                receipt_date=None,
            )
        ],
        not_before_me=None,
        filing_date=datetime.date(2018, 12, 28),
    )
    assert case_details.case == expected
    # We validate that our HTML is minimal and complete
    case_details2 = CaseDetails(case_details.html)
    assert (
        case_details2.html == case_details.html
    )  # Further minification can obviously not happen
    assert (
        case_details2.case == case_details.case
    )  # and the parser output should be equivalent

    # Validate that we have minified the HTML by a factor of 2
    assert len(case_details_html) / len(case_details.html) > 2
